### PR TITLE
[ENH] add page to explain how to create a default model for a dataset

### PR DESCRIPTION
**Pull request by Remi-Gau**

### CODE REVIEW

**Comment by effigies** [comment]
@Remi-Gau Meant to push this to mine and open a PR against your (after fixing the bad merge). Feel free to force-push back to a state you like, if you disagree with these changes.

**Comment by Remi-Gau** [comment]
> @Remi-Gau Meant to push this to mine and open a PR against yours (after fixing the bad merge). Feel free to force-push back to a state you like, if you disagree with these changes.

looks good to me

should I intersphinx bids.matlab too?

**Comment by effigies** [comment]
> should I intersphinx bids.matlab too?

Sure! I didn't realize you could...

**Comment by effigies** [comment]
Ah, I think I see. We need to use `sphinxcontrib-matlabdomain` and the `{mat:meth}` directive. Neat!

**Pull request merged**
