### PR TITLE
added banner

### PR DESCRIPTION
**Pull request by bendhouseart**
Added banner, not a mkdocs site...yet.

### CODE REVIEW

**Review by iamdamion — APPROVED** [review]
looks good!

**Comment by iamdamion** [comment]
two checks failed though.

**Comment by bendhouseart** [comment]
> two checks failed though.

Gotta love bitrot! Fixed!

**Comment by bendhouseart** [comment]
@adelavega the banner change happened here ;)

**Comment by adelavega** [comment]
@effigies reverted this. See: https://github.com/bids-standard/bids-website/issues/432

**Comment by bendhouseart** [comment]
Reopening if only to fix the CI.

**Pull request merged**
