### PR TITLE
Add .zenodo

### PR DESCRIPTION
**Pull request by adelavega**
Created .zenodo file, including all contributors to this repo, and those author listed on the original BIDS StatsModels doc

### CODE REVIEW

**Comment by effigies** [comment]
Doesn't Zenodo respect citation.cff? @Remi-Gau added that.

On my phone. Will look into this tomorrow.

**Comment by adelavega** [comment]
Oh, I didn't see that. No clue. either way there's some additional people to add

**Comment by Remi-Gau** [comment]
Yup zenodo will be fine with citation.cff.

Best to update the one we have.

**Comment by adelavega** [comment]
Oh, okay, well actually looks like the other one is complete... duh! Fun waste of time today :)

**Pull request closed without merging**
