### PR TITLE
ENH: Update JSON reference to show the loaded BIDSStatsModel object

### PR DESCRIPTION
**Pull request by effigies**
The idea is to give a better sense of the hierarchy. Screenshot, since we don't have RTD PR builds going.

Screenshot from 2022-05-12 22-29-33
Screenshot from 2022-05-12 22-29-42

### CODE REVIEW

**Comment by effigies** [comment]
@Remi-Gau Could I bug you for a review? This will require re-running `pip install -r requirements.txt` in your environment.

**Comment by Remi-Gau** [comment]
I must be missing something because I am not seeing what you are.

But I have had problems getting stuff to work locally before so it may be a case of PIBKAC.

Running things in a virtual env with python 3.8

<details><summary> <b>pip list output</b> </summary><br>

Package                       Version
----------------------------- -----------
alabaster                     0.7.12
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     2.0.5
attrs                         21.4.0
autodoc-pydantic              1.6.2
Babel                         2.10.1
backcall                      0.2.0
beautifulsoup4                4.11.1
black                         22.3.0
bleach                        5.0.0
bsmschema                     0.0.2
certifi                       2021.10.8
cffi                          1.15.0
charset-normalizer            2.0.12
click                         8.1.3
colorama                      0.4.4
debugpy                       1.6.0
decorator                     5.1.1
defusedxml                    0.7.1
docutils                      0.16
entrypoints                   0.4
executing                     0.8.3
fastjsonschema                2.15.3
gitdb                         4.0.9
GitPython                     3.1.27
greenlet                      1.1.2
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.3
importlib-resources           5.7.1
ipykernel                     6.13.0
ipython                       8.3.0
ipython-genutils              0.2.0
ipywidgets                    7.7.0
jedi                          0.18.1
Jinja2                        3.0.3
jsonschema                    3.2.0
jupyter-book                  0.12.3
jupyter-cache                 0.4.3
jupyter-client                7.3.0
jupyter-core                  4.10.0
jupyter-server                1.17.0
jupyter-server-mathjax        0.2.5
jupyter-sphinx                0.3.2
jupyterlab-pygments           0.2.2
jupyterlab-widgets            1.1.0
jupytext                      1.13.8
latexcodec                    2.0.1
linkify-it-py                 1.0.3
markdown-it-py                1.1.0
MarkupSafe                    2.1.1
matplotlib-inline             0.1.3
mdit-py-plugins               0.2.8
mistune                       0.8.4
mypy-extensions               0.4.3
myst-nb                       0.13.2
myst-parser                   0.15.2
nbclient                      0.5.13
nbconvert                     6.5.0
nbdime                        3.1.1
nbformat                      5.4.0
nest-asyncio                  1.5.5
notebook                      6.4.11
packaging                     21.3
pandocfilters                 1.5.0
parso                         0.8.3
pathspec                      0.9.0
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           22.1
platformdirs                  2.5.2
prometheus-client             0.14.1
prompt-toolkit                3.0.29
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
pybtex                        0.24.0
pybtex-docutils               1.0.1
pycparser                     2.21
pydantic                      1.9.0
pydata-sphinx-theme           0.7.2
pyee                          8.2.2
Pygments                      2.12.0
pyparsing                     3.0.8
pyppeteer                     1.0.2
pyrsistent                    0.18.1
python-dateutil               2.8.2
pytz                          2022.1
PyYAML                        6.0
pyzmq                         22.3.0
requests                      2.27.1
Send2Trash                    1.8.0
setuptools                    62.0.0
six                           1.16.0
smmap                         5.0.0
sniffio                       1.2.0
snowballstemmer               2.2.0
soupsieve                     2.3.2.post1
Sphinx                        4.5.0
sphinx-book-theme             0.1.10
sphinx-comments               0.0.3
sphinx-copybutton             0.5.0
sphinx-external-toc           0.2.4
sphinx-jupyterbook-latex      0.4.6
sphinx-multitoc-numbering     0.1.3
sphinx-panels                 0.6.0
sphinx-thebe                  0.1.2
sphinx-togglebutton           0.3.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-bibtex          2.4.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    1.4.36
stack-data                    0.2.0
terminado                     0.13.3
tinycss2                      1.1.1
toml                          0.10.2
tomli                         2.0.1
tornado                       6.1
tqdm                          4.64.0
traitlets                     5.1.1
typing_extensions             4.2.0
uc-micro-py                   1.0.1
urllib3                       1.26.9
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.3.2
websockets                    10.3
wheel                         0.37.1
widgetsnbextension            3.6.0
zipp                          3.8.0

  </pre>
</details>

**Comment by effigies** [comment]
Is your `bsmschema` installed in editable mode?

**Comment by Remi-Gau** [comment]
tried with conda and now things are ok.

**Comment by Remi-Gau** [comment]
Overall I think this helps...

But...

I am starting to wonder if the mental the mental gymnastic of "converting" from python lingo to json lingo is not going to be a bit much in the long run.

True that this part of the spec bids-stats may not be for the widest audience but it does raises the entry level.

Is that a side effect of "encoding" the model in pydantic?

That should not stop and merge and we discuss this at a later stage.

**Review by Remi-Gau — APPROVED** [review]

**Comment by effigies** [comment]
> I am starting to wonder if the mental the mental gymnastic of "converting" from python lingo to json lingo is not going to be a bit much in the long run.

Yeah, I wish I could declare a type `Object[valtype]` but I don't understand `typing` well enough to do it right now.

> True that this part of the spec bids-stats may not be for the widest audience but it does raises the entry level.
> 
> Is that a side effect of "encoding" the model in pydantic?

Yup. For auto-generating these docs, we can only do so much to manipulate without diving into writing custom Sphinx extensions.

**Comment by effigies** [comment]
Okay, I'll go ahead and merge so we don't have too many open things going. Let's open issues for proposed improvements.

**Pull request merged**
